### ISSUE TITLE
KeyError : 'Style'

### ISSUE THREAD

**Issue by kmlbgn** [sueszli/notionSnapshot#10]
Notion seem to have changed its table view structure which now triggers an error when being scrapped. 
(Running notionSnapshot on Linux here)

Issue related to : https://github.com/leoncvlt/loconotion/issues/141

<img width="784" alt="image" src="https://github.com/sueszli/notionSnapshot/assets/59659182/2107af5d-a897-4b76-9108-98b5e66d5b7f">

**Comment by sueszli** [comment]
hey there - i probably won't get to work on this project any time soon but i'll gladly review PRs. thanks!
