### ISSUE TITLE
config.toml ? 

### ISSUE THREAD

**Issue by kmlbgn** [sueszli/notionSnapshot#12]
As a user of loconotion, I'm using the config.toml extensively, especially for its code injections features. Has this been deprecated in this version ?

**Comment by sueszli** [comment]
You could call it deprecated, but I'm following a different philosophy here.

The goal here is to have more simplicity and maintainability at the cost of reduced configurability and customizability.

This is how this repository basically just consists of a single file with 500ish lines of code :)

**Comment by sueszli** [comment]
You can edit the .js / .css files for code injection.
