### ISSUE TITLE
Style and images not correct

### ISSUE THREAD

**Issue by sca1235** [sueszli/notionSnapshot#15]
the sidebar and images are messed up. they are max 100% size. On notion has ability to size properly.

This is what notionsnapshot made: https://support-trustswiftly-com.pages.dev/

This is the public url: https://trustswiftly.notion.site/Trust-Swiftly-8b7ba62a1ec640588e01c20e4c0bb2cb

can see the images are full size so look weird. page width is also weird.

**Comment by sueszli** [comment]
thanks @sca1235!

nice job
