### ISSUE TITLE
Breadcrumbs without links

### ISSUE THREAD

**Issue by faxenoff** [sueszli/notionSnapshot#6]
Links (<a/>) are lost in the breadcrumbs. Can you fix it?
The root link is especially important. Without it, you can't get back to the main page in a simple way.
Thank you!

![image](https://github.com/sueszli/notionSnapshot/assets/120191/67c4d73e-9eb1-4c52-80f0-2f479b7264a3)

**Comment by sueszli** [comment]
hey there - i probably won't get to work on this project any time soon but i'll gladly review PRs. thanks!
