### ISSUE TITLE
Failed to download chromedrive

### ISSUE THREAD

**Issue by alexchenzl** [sueszli/notionSnapshot#7]
When I run test.sh, it failed to download the chromedriver.

I found out the reason is the chromedriver download link has been changed since version M115. Pls refer to https://sites.google.com/chromium.org/driver/ for more information.

My current workaround is manually download chrome and chromedriver, and specify the executable_path in driver.py mannually. But I think there should be a generic solution.

My environment is Ubuntu 20.04.

**Comment by sueszli** [comment]
hey there - i probably won't get to work on this project any time soon but i'll gladly review PRs. thanks!

**Comment by sueszli** [comment]
also: selenium is generally a terrible choice for webscraping. Playwright would be much smarter.

**Comment by sueszli** [comment]
I created a Dockerfile. It's still a work in progress but has effectively resolved this issue.
