### ISSUE TITLE
Forbidden to download assets

### ISSUE THREAD

**Issue by alexchenzl** [sueszli/notionSnapshot#8]
When I tried to scrape a public notion page, it reports 403 status code when downloading assets.

But if I replaced all "www.notion.so" with "xxx.notion.site", and scrape it again. The 403 status code disappeared.

I suggest to extract the subdomain from the notion page URL instead of using "www.notion.so" to access notion page assets.

**Comment by sueszli** [comment]
hey there - i probably won't get to work on this project any time soon but i'll gladly review PRs. thanks!

**Comment by sueszli** [comment]
should be fixed now ^^
